# syntax=docker/dockerfile:1
# Generated by springdocker — https://github.com/mnafshin/springdocker
# Java 25 | build-tool: maven

ARG TARGETPLATFORM
ARG BUILDPLATFORM

FROM --platform=$BUILDPLATFORM eclipse-temurin:25-jdk AS build
WORKDIR /app
COPY mvnw pom.xml ./
COPY .mvn ./.mvn
RUN chmod +x mvnw
COPY src ./src
RUN --mount=type=cache,sharing=locked,target=/root/.m2 ./mvnw -B -q package -DskipTests

FROM --platform=$BUILDPLATFORM eclipse-temurin:25-jdk AS jre-builder
WORKDIR /jre
COPY --from=build /app/target/*.jar app.jar
RUN jdeps --ignore-missing-deps --recursive --multi-release 25 --print-module-deps app.jar > modules.txt
ARG MUSTHAVE_MODULES=""
RUN set -eux; \
    MODULES=$( (tr ',' '\n' < modules.txt; printf '%s\n' "$MUSTHAVE_MODULES" | tr ',' '\n') \
      | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$' | sort -u | paste -sd, -); \
    jlink --add-modules "$MODULES" --strip-debug --no-man-pages --no-header-files --compress=2 --output /opt/java

FROM --platform=$TARGETPLATFORM eclipse-temurin:25-jre
RUN groupadd --system --gid 1001 javauser && useradd --system --uid 1001 --gid 1001 --no-create-home --shell /usr/sbin/nologin javauser
RUN install -d -o 1001 -g 1001 -m 755 /app && install -d -o 1001 -g 1001 -m 1777 /tmp
WORKDIR /app
VOLUME /tmp
COPY --from=build --chown=1001:1001 /app/target/*.jar app.jar
EXPOSE 8080
EXPOSE 8081
COPY --from=jre-builder /opt/java /opt/java
ENV JAVA_HOME=/opt/java
ENV PATH="${JAVA_HOME}/bin:${PATH}"
USER 1001
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-XX:+ExitOnOutOfMemoryError", "-Djava.io.tmpdir=/tmp", "-jar", "app.jar"]
# Runtime hardening tip: run with --read-only --cap-drop=ALL --security-opt=no-new-privileges --tmpfs /tmp
