# syntax=docker/dockerfile:1
# Generated by springdocker — https://github.com/mnafshin/springdocker
# Java 25 | build-tool: maven

ARG TARGETPLATFORM
ARG BUILDPLATFORM

ARG SOURCE_DATE_EPOCH=0

ARG OCI_SOURCE=""
ARG OCI_REVISION=""
ARG OCI_CREATED=""

FROM --platform=$BUILDPLATFORM eclipse-temurin:25-jdk@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f AS build
WORKDIR /app
COPY mvnw pom.xml ./
COPY .mvn ./.mvn
RUN chmod +x mvnw
COPY src ./src
RUN --mount=type=cache,sharing=locked,target=/root/.m2 ./mvnw -B -q package -DskipTests
RUN java -Djarmode=layertools -jar /app/target/*.jar extract --destination /layers

RUN install -d /tmp/sbom && printf '{"spdxVersion":"SPDX-2.3","name":"springdocker-generated-image"}' > /tmp/sbom/spdx.json

FROM --platform=$BUILDPLATFORM eclipse-temurin:25-jdk-alpine AS jre-builder
WORKDIR /jre
COPY --from=build /app/target/*.jar app.jar
RUN jdeps --ignore-missing-deps --recursive --multi-release 25 --print-module-deps app.jar > modules.txt
ARG MUSTHAVE_MODULES="java.base,java.desktop,java.instrument,java.logging,java.sql,java.xml,java.naming,java.management,java.security.jgss,jdk.crypto.ec,jdk.unsupported"
RUN set -eux; \
    MODULES=$( (tr ',' '\n' < modules.txt; printf '%s\n' "$MUSTHAVE_MODULES" | tr ',' '\n') \
      | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$' | sort -u | paste -sd, -); \
    jlink --add-modules "$MODULES" --strip-debug --no-man-pages --no-header-files --compress=2 --output /jre/out

FROM --platform=$TARGETPLATFORM alpine:3.21
RUN apk add --no-cache shadow
RUN addgroup -S -g 1001 javauser && adduser -S -u 1001 -G javauser -H -D javauser
RUN install -d -o 1001 -g 1001 -m 755 /app && install -d -o 1001 -g 1001 -m 1777 /tmp
WORKDIR /app
VOLUME /tmp
EXPOSE 8080
EXPOSE 8081
COPY --from=build --chown=1001:1001 /layers/dependencies/ ./
COPY --from=build --chown=1001:1001 /layers/spring-boot-loader/ ./
COPY --from=build --chown=1001:1001 /layers/snapshot-dependencies/ ./
COPY --from=build --chown=1001:1001 /layers/application/ ./
LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}"
COPY --from=build /tmp/sbom/spdx.json /usr/share/sbom/spdx.json
ENV SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH}"

COPY --from=jre-builder /jre/out /opt/java
ENV JAVA_HOME=/opt/java
ENV PATH="${JAVA_HOME}/bin:${PATH}"
USER 1001
STOPSIGNAL SIGTERM
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-XX:+ExitOnOutOfMemoryError", "-Djava.io.tmpdir=/tmp", "org.springframework.boot.loader.launch.JarLauncher"]
# Runtime hardening tip: run with --read-only --cap-drop=ALL --security-opt=no-new-privileges --tmpfs /tmp
