# syntax=docker/dockerfile:1
# Generated by springdocker — https://github.com/mnafshin/springdocker
# Java 25 | build-tool: maven

ARG TARGETPLATFORM
ARG BUILDPLATFORM

ARG SOURCE_DATE_EPOCH=0

ARG OCI_SOURCE=""
ARG OCI_REVISION=""
ARG OCI_CREATED=""

FROM --platform=$BUILDPLATFORM eclipse-temurin:25-jdk@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f AS build
WORKDIR /app
COPY mvnw pom.xml ./
COPY .mvn ./.mvn
RUN chmod +x mvnw
COPY src ./src
RUN --mount=type=cache,sharing=locked,target=/root/.m2 ./mvnw -B -q package -DskipTests
RUN java -Djarmode=layertools -jar /app/target/*.jar extract --destination /layers

RUN install -d /tmp/sbom && printf '{"spdxVersion":"SPDX-2.3","name":"springdocker-generated-image"}' > /tmp/sbom/spdx.json

FROM --platform=$TARGETPLATFORM gcr.io/distroless/java25-debian13:nonroot
WORKDIR /app
VOLUME /tmp
EXPOSE 8080
EXPOSE 8081
COPY --from=build /layers/dependencies/ ./
COPY --from=build /layers/spring-boot-loader/ ./
COPY --from=build /layers/snapshot-dependencies/ ./
COPY --from=build /layers/application/ ./
LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}"
USER nonroot
COPY --from=build /tmp/sbom/spdx.json /usr/share/sbom/spdx.json
ENV SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH}"
STOPSIGNAL SIGTERM
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-XX:+ExitOnOutOfMemoryError", "-Djava.io.tmpdir=/tmp", "org.springframework.boot.loader.launch.JarLauncher"]
# Runtime hardening tip: run with --read-only --cap-drop=ALL --security-opt=no-new-privileges --tmpfs /tmp
