# syntax=docker/dockerfile:1
# Generated by springdocker — https://github.com/mnafshin/springdocker
# Java 25 | build-tool: maven
# recipe: native-aot
# scaffold: experimental native-image Dockerfile; not a production-ready springdocker workflow

ARG TARGETPLATFORM
ARG BUILDPLATFORM

ARG SOURCE_DATE_EPOCH=0

ARG OCI_SOURCE=""
ARG OCI_REVISION=""
ARG OCI_CREATED=""

FROM --platform=$BUILDPLATFORM ghcr.io/graalvm/native-image-community:25 AS build
WORKDIR /app
COPY mvnw pom.xml ./
COPY .mvn ./.mvn
RUN chmod +x mvnw
COPY src ./src
RUN --mount=type=cache,sharing=locked,target=/root/.m2 ./mvnw -B -q -Pnative -DskipTests native:compile
RUN java -Djarmode=layertools -jar /app/target/* extract --destination /layers

RUN install -d /tmp/sbom && printf '{"spdxVersion":"SPDX-2.3","name":"springdocker-generated-image"}' > /tmp/sbom/spdx.json

FROM --platform=$TARGETPLATFORM gcr.io/distroless/base-debian13:nonroot@sha256:ab7554b6d07ad354fad31957f8a1a813e65dfb93a8ad160568c79c3f2be6884f
WORKDIR /app
COPY --from=build /app/target/* /app/app
LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}"
COPY --from=build /tmp/sbom/spdx.json /usr/share/sbom/spdx.json
ENV SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH}"
STOPSIGNAL SIGTERM
ENTRYPOINT ["/app/app"]
