package io.github.mnafshin.springdocker.maven;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Renders a multi-stage Dockerfile from {@link PluginDockerfileOptions}.
 *
 * <p>Opinionated subset of the Python CLI generator — no toml, no benchmarks.
 */
public final class DockerfileRenderer {

    private static final String REPO = "https://github.com/mnafshin/springdocker";

    private DockerfileRenderer() {}

    public static String render(PluginDockerfileOptions options) {
        List<String> lines = new ArrayList<>();
        int java = options.javaVersion();
        String runtime = options.runtimeImage().toLowerCase(Locale.ROOT);

        lines.add("# syntax=docker/dockerfile:1");
        lines.add("# Generated by springdocker-maven-plugin — " + REPO);
        lines.add("# Java " + java + " | build-tool: maven | POM SSOT (ADR 0010)");
        if (!"jvm-balanced".equals(options.recipe())) {
            lines.add("# recipe: " + options.recipe());
        }
        lines.add("");
        lines.add("ARG TARGETPLATFORM");
        lines.add("ARG BUILDPLATFORM");
        lines.add("");

        // --- build ---
        lines.add("FROM --platform=$BUILDPLATFORM eclipse-temurin:" + java + "-jdk AS build");
        lines.add("WORKDIR /app");
        lines.add("COPY pom.xml .");
        lines.add("COPY src ./src");
        if ("spring-aot".equals(options.recipe())) {
            lines.add(
                    "RUN --mount=type=cache,sharing=locked,target=/root/.m2 "
                            + "mvn -B -DskipTests package spring-boot:process-aot package"
            );
        } else {
            lines.add(
                    "RUN --mount=type=cache,sharing=locked,target=/root/.m2 "
                            + "mvn -B -DskipTests package"
            );
        }
        lines.add(
                "RUN JAR=\"$(ls target/*.jar | grep -v '\\.original$' | grep -v '\\-sources\\.jar$' "
                        + "| grep -v '\\-javadoc\\.jar$' | head -n 1)\" "
                        + "&& cp \"$JAR\" /app/application.jar"
        );
        if (options.useLayeredJar()) {
            lines.add(
                    "RUN java -Djarmode=tools -jar /app/application.jar extract --layers "
                            + "--destination /app/extracted"
            );
        }
        lines.add("");

        boolean customJlink = options.useJlink() && !"temurin".equals(runtime);
        if (customJlink) {
            lines.add("FROM --platform=$BUILDPLATFORM eclipse-temurin:" + java + "-jdk AS jlink");
            lines.add(
                    "RUN jlink --verbose --strip-debug --no-header-files --no-man-pages "
                            + "--compress=2 "
                            + "--add-modules java.base,java.logging,java.naming,java.desktop,"
                            + "java.management,java.security.jgss,java.instrument,jdk.unsupported,"
                            + "jdk.crypto.ec "
                            + "--output /custom-jre"
            );
            lines.add("");
        }

        // --- runtime ---
        appendRuntime(lines, options, runtime, customJlink);
        lines.add("");
        return String.join("\n", lines);
    }

    private static void appendRuntime(
            List<String> lines,
            PluginDockerfileOptions options,
            String runtime,
            boolean customJlink
    ) {
        int java = options.javaVersion();
        switch (runtime) {
            case "distroless" -> {
                if (customJlink) {
                    lines.add(
                            "FROM --platform=$TARGETPLATFORM gcr.io/distroless/base-debian12:nonroot AS runtime"
                    );
                } else {
                    lines.add(
                            "FROM --platform=$TARGETPLATFORM gcr.io/distroless/java"
                                    + java
                                    + "-debian12:nonroot AS runtime"
                    );
                }
            }
            case "temurin" -> lines.add(
                    "FROM --platform=$TARGETPLATFORM eclipse-temurin:" + java + "-jre AS runtime"
            );
            case "alpine" -> lines.add(
                    "FROM --platform=$TARGETPLATFORM eclipse-temurin:" + java + "-jre-alpine AS runtime"
            );
            case "debian-slim" -> lines.add(
                    "FROM --platform=$TARGETPLATFORM debian:bookworm-slim AS runtime"
            );
            case "ubuntu" -> lines.add(
                    "FROM --platform=$TARGETPLATFORM ubuntu:24.04 AS runtime"
            );
            default -> throw new IllegalArgumentException("unsupported runtimeImage: " + runtime);
        }

        lines.add("WORKDIR /app");

        if (customJlink) {
            lines.add("COPY --from=jlink /custom-jre /jre");
        } else if ("debian-slim".equals(runtime) || "ubuntu".equals(runtime)) {
            // OS base without a JRE: require jlink or fail closed by copying nothing useful —
            // when useJlink is false, still copy Temurin JRE via a mini stage is heavy;
            // document that debian-slim/ubuntu expect useJlink=true. If false, copy jar only
            // and use a warning comment.
            if (!options.useJlink()) {
                lines.add("# WARNING: debian-slim/ubuntu without useJlink need a JRE; prefer temurin or enable useJlink");
            }
        }

        if (options.useLayeredJar()) {
            String chown = options.nonRoot() && !"distroless".equals(runtime) ? "--chown=1001:1001 " : "";
            lines.add("COPY " + chown + "--from=build /app/extracted/dependencies/ ./");
            lines.add("COPY " + chown + "--from=build /app/extracted/spring-boot-loader/ ./");
            lines.add("COPY " + chown + "--from=build /app/extracted/snapshot-dependencies/ ./");
            lines.add("COPY " + chown + "--from=build /app/extracted/application/ ./");
        } else {
            String chown = options.nonRoot() && !"distroless".equals(runtime) ? "--chown=1001:1001 " : "";
            lines.add("COPY " + chown + "--from=build /app/application.jar app.jar");
        }

        if (options.nonRoot() && !"distroless".equals(runtime)) {
            if ("alpine".equals(runtime) || "temurin".equals(runtime)) {
                lines.add("USER 1001");
            } else if ("debian-slim".equals(runtime) || "ubuntu".equals(runtime)) {
                lines.add("RUN useradd --system --uid 1001 --no-create-home appuser");
                lines.add("USER 1001");
            }
        }

        if ("distroless".equals(runtime) && customJlink) {
            if (options.useLayeredJar()) {
                lines.add("ENTRYPOINT [\"/jre/bin/java\", \"org.springframework.boot.loader.launch.JarLauncher\"]");
            } else {
                lines.add("ENTRYPOINT [\"/jre/bin/java\", \"-jar\", \"app.jar\"]");
            }
        } else if ("distroless".equals(runtime)) {
            if (options.useLayeredJar()) {
                lines.add("ENTRYPOINT [\"java\", \"org.springframework.boot.loader.launch.JarLauncher\"]");
            } else {
                lines.add("ENTRYPOINT [\"java\", \"-jar\", \"app.jar\"]");
            }
        } else if (customJlink) {
            if (options.useLayeredJar()) {
                lines.add("ENTRYPOINT [\"/jre/bin/java\", \"org.springframework.boot.loader.launch.JarLauncher\"]");
            } else {
                lines.add("ENTRYPOINT [\"/jre/bin/java\", \"-jar\", \"/app/app.jar\"]");
            }
        } else if (options.useLayeredJar()) {
            lines.add("ENTRYPOINT [\"java\", \"org.springframework.boot.loader.launch.JarLauncher\"]");
        } else {
            lines.add("ENTRYPOINT [\"java\", \"-jar\", \"/app/app.jar\"]");
        }

        // Distroless has no shell → no HEALTHCHECK (matches CLI behavior).
        if (!"distroless".equals(runtime)) {
            lines.add(
                    "HEALTHCHECK --interval=15s --timeout=3s --start-period=20s --retries=3 "
                            + "CMD curl -fsS http://localhost:8080/actuator/health/readiness || exit 1"
            );
        }
    }
}
