package io.github.mnafshin.springdocker.maven;

/**
 * One-way export of plugin options to {@code .springdocker.toml} for CLI adoption.
 *
 * <p>Direction is always POM → toml. Never the reverse.
 */
public final class TomlConfigExporter {

    private TomlConfigExporter() {}

    public static String render(PluginDockerfileOptions options) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by springdocker-maven-plugin:export-config (POM SSOT → CLI bridge)\n");
        sb.append("# Edit the Maven plugin configuration as source of truth; re-export after changes.\n");
        sb.append("# See docs/adr/0010-pom-gradle-ssot-java-builder.md\n\n");
        sb.append("[project]\n");
        sb.append("build_tool = \"maven\"\n\n");
        sb.append("[dockerfile]\n");
        sb.append("output = ").append(tomlString(options.output())).append('\n');
        sb.append("java_version = ").append(options.javaVersion()).append('\n');
        sb.append("recipe = ").append(tomlString(options.recipe())).append('\n');
        sb.append("runtime_image = ").append(tomlString(options.runtimeImage())).append('\n');
        sb.append("use_jlink = ").append(options.useJlink()).append('\n');
        sb.append("use_layered_jar = ").append(options.useLayeredJar()).append('\n');
        sb.append("non_root = ").append(options.nonRoot()).append('\n');
        return sb.toString();
    }

    private static String tomlString(String value) {
        return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }
}
