# syntax=docker/dockerfile:1
# Generated by springdocker — https://github.com/mnafshin/springdocker
# Java 21 | build-tool: gradle

ARG SOURCE_DATE_EPOCH=0

ARG OCI_SOURCE=""
ARG OCI_REVISION=""
ARG OCI_CREATED=""

FROM --platform=$BUILDPLATFORM eclipse-temurin:21-jdk@sha256:b9142586f9712700c6c9e07adcedfb18608b1a3a056e4001423a3354adfa9d80 AS build
WORKDIR /app
COPY gradlew build.gradle.kts settings.gradle.kts ./
COPY gradle ./gradle
RUN chmod +x gradlew
COPY src ./src
RUN ./gradlew --no-daemon bootJar -x test
RUN set -eux; \
    boot_jar=$(ls build/libs/*.jar | grep -v -- '-plain.jar$' | head -1); \
    test -n "$boot_jar"; \
    cp "$boot_jar" build/libs/application.jar
RUN java -Djarmode=tools -jar /app/build/libs/application.jar extract --layers --destination /layers
RUN mkdir -p /cds-work && \
    cp -a /layers/dependencies /layers/spring-boot-loader /layers/snapshot-dependencies /cds-work/ && \
    cp -a /layers/application/. /cds-work/ && \
    cd /cds-work && \
    java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar application.jar || true
RUN install -d /tmp/sbom && printf '{"spdxVersion":"SPDX-2.3","name":"springdocker-generated-image"}' > /tmp/sbom/spdx.json

FROM --platform=$TARGETPLATFORM gcr.io/distroless/java21-debian12:nonroot@sha256:7e37784d94dccbf5ccb195c73b295f5ad00cd266512dfbac12eb9c3c28f8077d
WORKDIR /app
VOLUME /tmp
EXPOSE 8080
EXPOSE 8081
COPY --from=build /layers/dependencies/ ./
COPY --from=build /layers/spring-boot-loader/ ./
COPY --from=build /layers/snapshot-dependencies/ ./
COPY --from=build /layers/application/ ./
COPY --from=build /cds-work/application.jsa /app/application.jsa
LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}"
COPY --from=build /tmp/sbom/spdx.json /usr/share/sbom/spdx.json
ENV SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH}"
STOPSIGNAL SIGTERM
ENTRYPOINT ["java", "-XX:SharedArchiveFile=application.jsa", "-jar", "application.jar"]
# Runtime hardening tip: run with --read-only --cap-drop=ALL --security-opt=no-new-privileges --tmpfs /tmp
