from __future__ import annotations

import unittest
from dataclasses import fields

from tests.test_support import add_src_to_path

add_src_to_path()

from springdocker.dockerfile import (
    JLINK_BASELINE_MODULES,
    DockerfileOptions,
    build_dockerfile,
    merge_jlink_must_have_modules,
)


class DockerfileTemplateRenderingTests(unittest.TestCase):
    def test_template_render_keeps_generated_header(self) -> None:
        rendered = build_dockerfile(DockerfileOptions(build_tool="maven", java_version=21))
        self.assertIn("# Generated by springdocker — https://github.com/mnafshin/springdocker", rendered)
        self.assertIn("# Java 21 | build-tool: maven", rendered)

    def test_to_spec_maps_all_option_fields(self) -> None:
        option_field_names = {field.name for field in fields(DockerfileOptions)}
        self.assertEqual(
            option_field_names,
            {
                "build_tool",
                "recipe",
                "java_version",
                "use_buildkit_cache",
                "use_jlink",
                "non_root",
                "tuned_jvm_flags",
                "must_have_modules",
                "jlink_baseline_modules",
                "runtime_image",
                "platform_aware",
                "healthcheck_path",
                "include_oci_labels",
                "include_stopsignal",
                "include_embedded_sbom",
                "include_reproducible_controls",
                "use_layered_jar",
                "enable_appcds",
                "enable_jep483_aot_cache",
            },
        )

    def test_merge_jlink_must_have_modules_appends_baseline_without_duplicates(self) -> None:
        merged = merge_jlink_must_have_modules(("java.naming", "jdk.crypto.ec"), JLINK_BASELINE_MODULES)
        self.assertEqual(
            merged,
            ("java.naming", "jdk.crypto.ec", "java.desktop", "java.logging"),
        )

    def test_build_dockerfile_omits_baseline_when_disabled(self) -> None:
        rendered = build_dockerfile(
            DockerfileOptions(
                build_tool="maven",
                java_version=25,
                must_have_modules=("jdk.crypto.ec",),
                jlink_baseline_modules=(),
            )
        )
        self.assertIn('ARG MUSTHAVE_MODULES="jdk.crypto.ec"', rendered)
        self.assertNotIn("java.desktop", rendered)

    def test_alpine_runtime_uses_musl_jdk_for_jlink_builder(self) -> None:
        rendered = build_dockerfile(
            DockerfileOptions(
                build_tool="maven",
                java_version=25,
                runtime_image="alpine",
                enable_appcds=False,
            )
        )
        self.assertIn("FROM --platform=$BUILDPLATFORM eclipse-temurin:25-jdk-alpine AS jre-builder", rendered)
        self.assertIn("FROM --platform=$TARGETPLATFORM alpine:3.21", rendered)

    def test_debian_slim_runtime_renders_with_jlink(self) -> None:
        rendered = build_dockerfile(
            DockerfileOptions(
                build_tool="maven",
                java_version=25,
                runtime_image="debian-slim",
                enable_appcds=False,
            )
        )
        self.assertIn("debian:bookworm-slim", rendered)
        self.assertIn("COPY --from=jre-builder /jre/out /opt/java", rendered)
        self.assertNotIn("ArchiveClassesAtExit", rendered)

    def test_debian_slim_runtime_renders_with_vendor_jre_without_jlink(self) -> None:
        rendered = build_dockerfile(
            DockerfileOptions(
                build_tool="maven",
                java_version=25,
                runtime_image="debian-slim",
                use_jlink=False,
                enable_appcds=False,
            )
        )
        self.assertIn("debian:bookworm-slim", rendered)
        self.assertIn("FROM eclipse-temurin:25-jre", rendered)
        self.assertIn("AS vendor-jre", rendered)
        self.assertIn("COPY --from=vendor-jre /opt/java/openjdk /opt/java", rendered)
        self.assertNotIn("AS jre-builder", rendered)

    def test_jep483_aot_cache_stage_renders(self) -> None:
        rendered = build_dockerfile(
            DockerfileOptions(
                build_tool="maven",
                java_version=25,
                enable_jep483_aot_cache=True,
                enable_appcds=False,
            )
        )
        self.assertIn("AS aot-trainer", rendered)
        self.assertIn("-XX:AOTCacheOutput=/app/app.aot", rendered)
        self.assertIn("-XX:AOTCache=/app/app.aot", rendered)
        self.assertNotIn("ArchiveClassesAtExit", rendered)

    def test_toggle_markers_render_as_expected(self) -> None:
        rendered = build_dockerfile(
            DockerfileOptions(
                build_tool="maven",
                include_oci_labels=False,
                include_stopsignal=False,
                include_embedded_sbom=False,
                include_reproducible_controls=False,
                use_layered_jar=False,
                enable_appcds=False,
                healthcheck_path="/actuator/health/readiness",
            )
        )
        self.assertNotIn("org.opencontainers.image.source", rendered)
        self.assertNotIn("STOPSIGNAL SIGTERM", rendered)
        self.assertNotIn("/usr/share/sbom/spdx.json", rendered)
        self.assertNotIn("SOURCE_DATE_EPOCH", rendered)
        self.assertNotIn("jarmode=layertools", rendered)
        self.assertIn('ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-XX:+ExitOnOutOfMemoryError", "-Djava.io.tmpdir=/tmp", "-jar", "app.jar"]', rendered)
        self.assertIn("HEALTHCHECK --interval=15s", rendered)

    def test_to_spec_groups_values(self) -> None:
        options = DockerfileOptions(
            build_tool="gradle",
            recipe="spring-aot",
            java_version=21,
            use_buildkit_cache=False,
            use_jlink=False,
            non_root=False,
            tuned_jvm_flags=False,
            must_have_modules=("java.naming",),
            runtime_image="distroless",
            platform_aware=False,
            healthcheck_path="/health",
            include_oci_labels=False,
            include_stopsignal=False,
            include_embedded_sbom=False,
            include_reproducible_controls=False,
            use_layered_jar=False,
            enable_appcds=False,
        )
        spec = options.to_spec()
        self.assertEqual(spec.build_tool, "gradle")
        self.assertEqual(spec.java_version, 21)
        self.assertEqual(spec.build.recipe, "spring-aot")
        self.assertFalse(spec.build.use_buildkit_cache)
        self.assertFalse(spec.build.use_jlink)
        self.assertEqual(spec.build.must_have_modules, ("java.naming",))
        self.assertEqual(spec.runtime.runtime_image, "distroless")
        self.assertFalse(spec.runtime.platform_aware)
        self.assertFalse(spec.runtime.non_root)
        self.assertEqual(spec.runtime.healthcheck_path, "/health")
        self.assertFalse(spec.supply_chain.include_oci_labels)
        self.assertFalse(spec.supply_chain.include_stopsignal)
        self.assertFalse(spec.supply_chain.include_embedded_sbom)
        self.assertFalse(spec.supply_chain.include_reproducible_controls)


if __name__ == "__main__":
    unittest.main()
